# Generated by Django 3.2.9 on 2021-11-25 00:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True, verbose_name='Объекты')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Номер счёта')),
                ('shipping_date', models.DateField(default=datetime.date.today, verbose_name='Дата отгрузки')),
                ('create_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Дата создания счета')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Счёт',
                'verbose_name_plural': 'Счета',
                'ordering': ['shipping_date'],
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('IN', 'Приход'), ('OUT', 'Расход')], default='IN', max_length=3, verbose_name='Тип операции')),
                ('shipping_date', models.DateField(default=datetime.date.today, verbose_name='Дата операции')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('unit', models.CharField(choices=[('TH', 'шт.'), ('KG', 'кг.'), ('LT', 'л.')], default='TH', max_length=2, verbose_name='Единица измерения')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.category', verbose_name='Категория позиции')),
            ],
            options={
                'verbose_name': 'Позиция',
                'verbose_name_plural': 'Позиции',
                'ordering': ['title', 'provider'],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Количество')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=11, verbose_name='Цена за единицу')),
                ('price_sum', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, verbose_name='Цена общая')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.entity', verbose_name='Объект')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.invoice', verbose_name='Счёт')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.position', verbose_name='Позиция')),
            ],
            options={
                'verbose_name': 'Наличие на складе',
                'verbose_name_plural': 'Наличие на складе',
            },
        ),
        migrations.AddField(
            model_name='position',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.provider', verbose_name='Поставщик'),
        ),
        migrations.CreateModel(
            name='OperationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Количество')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=11, verbose_name='Цена за единицу')),
                ('price_sum', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, verbose_name='Цена общая')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.entity', verbose_name='Объект')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.invoice', verbose_name='Счёт')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.operation', verbose_name='Операция')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.position', verbose_name='Позиция')),
            ],
            options={
                'verbose_name': 'Список операций по позициям',
                'verbose_name_plural': 'Список операций по позициям',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.provider', verbose_name='Поставщик'),
        ),
    ]
